debug: true
spring:
  application:
    name: RegistrationLogin
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/valuationhub8?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: xolipdphfgkkmftw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: 10010mayur@gmail.com
